name: Draft release from JSON manifest

on:
  push:
    branches:
      - main
    paths:
      - "manifest.json"

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # to fetch tags

      - name: Extract version from JSON manifest
        id: get_version
        run: |
          VERSION=$(jq --raw-output '.version' manifest.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create git tag
        run: |
          git tag ${{ steps.get_version.outputs.version }}
          git push origin ${{ steps.get_version.outputs.version }}

      - name: Draft GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.version }} \
            --title=${{ steps.get_version.outputs.version }} \
            --draft \
            manifest.json theme.css
